apiVersion: v1
kind: ConfigMap
metadata:
  name: minispring-config
  namespace: default
data:
  application-k8s.yaml: |
    minispring:
      title: "minikube + springboot with configmap"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minispring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minispring
  template:
    metadata:
      labels:
        app: minispring
    spec:
      containers:
        - name: minispring
          image: registry.digitalocean.com/sds-do-cr01/minispring:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: minispring-config
      restartPolicy: Always